#!/usr/bin/env ruby
# frozen_string_literal: true

$PROGRAM_NAME =~ %r{/([a-zA-z]+)$}
prog = Regexp.last_match(1)

if ARGV.empty?
  require "buntumixer-help"
  exit true
else
  cmd = ARGV[0]
end

case cmd
when "help", "h"
  require "buntumixer-help"
when "using", "u"
  require "buntumixer-using"
when "clear"
  require "buntumixer-clear"
when "prepare", "prep", "p"
  require "buntumixer-prepare"
when "create"
  require "buntumixer-create"
when "apply"
  require "buntumixer-apply"
else
  puts "#{prog}: #{cmd} コマンドが見つかりません"
end
